/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Welcome_2RouteImport } from './routes/welcome_2'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as CountdownRouteImport } from './routes/countdown'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDayNumRouteImport } from './routes/day.$dayNum'

const Welcome_2Route = Welcome_2RouteImport.update({
  id: '/welcome_2',
  path: '/welcome_2',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownRoute = CountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayNumRoute = DayDayNumRouteImport.update({
  id: '/day/$dayNum',
  path: '/day/$dayNum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/welcome_2': typeof Welcome_2Route
  '/day/$dayNum': typeof DayDayNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/welcome_2': typeof Welcome_2Route
  '/day/$dayNum': typeof DayDayNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/welcome_2': typeof Welcome_2Route
  '/day/$dayNum': typeof DayDayNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countdown'
    | '/journey'
    | '/welcome'
    | '/welcome_2'
    | '/day/$dayNum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countdown'
    | '/journey'
    | '/welcome'
    | '/welcome_2'
    | '/day/$dayNum'
  id:
    | '__root__'
    | '/'
    | '/countdown'
    | '/journey'
    | '/welcome'
    | '/welcome_2'
    | '/day/$dayNum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountdownRoute: typeof CountdownRoute
  JourneyRoute: typeof JourneyRoute
  WelcomeRoute: typeof WelcomeRoute
  Welcome_2Route: typeof Welcome_2Route
  DayDayNumRoute: typeof DayDayNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome_2': {
      id: '/welcome_2'
      path: '/welcome_2'
      fullPath: '/welcome_2'
      preLoaderRoute: typeof Welcome_2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdown': {
      id: '/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof CountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayNum': {
      id: '/day/$dayNum'
      path: '/day/$dayNum'
      fullPath: '/day/$dayNum'
      preLoaderRoute: typeof DayDayNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountdownRoute: CountdownRoute,
  JourneyRoute: JourneyRoute,
  WelcomeRoute: WelcomeRoute,
  Welcome_2Route: Welcome_2Route,
  DayDayNumRoute: DayDayNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
